version: "3.8"
services:
  postgres:
    image: postgres:14.3
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    command: [ "postgres", "-c", "log_statement=all" ]
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - "./:/go/src/github.com/Armatorix/smallpaf"
    depends_on:
      - postgres
  web:
    build:
      dockerfile: Dockerfile.dev
      context: ./web
    ports:
      - "3000:3000"
    volumes:
      - "./web:/web"